[package]
name = "git-transport"
version = "0.1.0"
repository = "https://github.com/Byron/git-oxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated to implementing the git transport layer"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[lib]
doctest = false
test = false

[features]
serde1 = ["serde"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"]}
git-url = { version = "^0.1.0", path = "../git-url" }
quick-error = "2.0.0"
