[package]
name = "gitoxide"
description = "A command-line application for interacting with git repositories"
version = "1.0.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
license = "MIT"
edition = "2018"

[[bin]]
name="gio"
path="src/main.rs"
test = false
doctest = false

[dependencies]
git-repository = { version = "0.1.0", path = "git-repository" }
git-odb = { version = "0.1.0", path = "git-odb", default-features = false, features = ["fast-sha1"] }
anyhow = "1.0.31"
structopt = "0.3.14"

[profile.release]
overflow-checks = false
lto = "fat"
panic = 'abort'
codegen-units = 1
incremental = false

[workspace]
members = [
    "git-object",
    "git-odb",
    "git-repository",
    "git-transport",
    "demos"
]
