[package]
name = "grit-cli"
version = "1.0.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
license = "MIT"
edition = "2018"

[[bin]]
name="grit"
path="src/main.rs"
test = false
doctest = false

[dependencies]
failure = "0.1.1"
failure-tools = "4.0.2"
clap = "2.31.2"
git-core = { version = "0.1.0", path = "git-core" }

[profile.release]
panic = 'unwind'
incremental = false

[workspace]
members = [
    "git-odb",
    "git-core",
    "demos"
]
