[package]
name = "gitoxide-cli"
version = "1.0.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
license = "MIT"
edition = "2018"

[[bin]]
name="gio"
path="src/main.rs"
test = false
doctest = false

[dependencies]
git-core = { version = "0.1.0", path = "gitoxide-core" }
anyhow = "1.0.31"
structopt = "0.3.14"

[profile.release]
panic = 'unwind'
incremental = false

[workspace]
members = [
    "gitoxide-object",
    "gitoxide-odb",
    "gitoxide-core",
    "demos"
]
