[package]
name = "gitoxide"
description = "A command-line application for interacting with git repositories"
repository = "https://github.com/Byron/git-oxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
license = "MIT"
version = "0.1.0"
default-run = "gio"
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md"]

[[bin]]
name="gio"
path="src/porcelain-cli.rs"
test = false
doctest = false


[[bin]]
name="giop"
path="src/plumbing-cli.rs"
test = false
doctest = false

[features]
default = ["max"]

max = ["fast", "pretty-cli", "prodash/tui-renderer-crossterm", "prodash-line-renderer-crossterm"]
max-termion = ["fast", "pretty-cli", "prodash/tui-renderer-termion", "prodash-line-renderer-termion"]

lean = ["fast", "lean-cli", "prodash-line-renderer-crossterm"]
lean-termion = ["fast", "lean-cli", "prodash-line-renderer-termion"]

light = ["fast", "lean-cli"]
small = ["lean-cli"]

fast = ["git-features/parallel", "git-features/fast-sha1"]
pretty-cli = ["structopt",
              "git-features/progress-prodash",
              "gitoxide-core/serde1",
              "prodash/log-renderer",
              "prodash-tui-renderer",
              "prodash-line-renderer",
              "ctrlc",
              "prodash/localtime",
              "env_logger",
              "smol"]
lean-cli = ["argh", "git-features/progress-log", "env_logger"]

prodash-line-renderer-crossterm = ["prodash-line-renderer", "prodash/line-renderer-crossterm", "git-features/progress-prodash", "atty", "crosstermion"]
prodash-line-renderer-termion = ["prodash-line-renderer", "prodash/line-renderer-termion", "git-features/progress-prodash", "atty", "crosstermion"]

# internal
prodash-tui-renderer = ["prodash/tui-renderer"]
prodash-line-renderer = ["prodash/line-renderer"]


[dependencies]
anyhow = "1.0.31"

gitoxide-core = { version = "0.1.0", path = "gitoxide-core" }
git-features = { version = "0.1.0", path = "git-features" }

structopt = { version = "0.3.14", optional = true }
argh = { version = "0.1.3", optional = true, default-features = false }
prodash = { version = "7.0.2", optional = true, default-features = false }
smol = { version = "0.1.18", optional = true, default-features = false }
atty = { version = "0.2.14", optional = true, default-features = false }
env_logger = { version = "0.7.1", optional = true, default-features = false, features = ["humantime", "termcolor", "atty"] }
crosstermion = { version = "0.1.5", optional = true, default-features = false }
ctrlc = { version = "3.1.4", optional = true, default-features = false, features = ['termination'] }

[profile.release]
overflow-checks = false
lto = "fat"
panic = 'abort'
codegen-units = 1
incremental = false

[profile.release.build-override]
opt-level = 0

[workspace]
members = [
    "gitoxide-core",
    "git-features",
    "git-object",
    "git-odb",
    "git-repository",
    "git-transport",
    "demos"
]
