[build.env]
passthrough = [
    "CI",
    "GITHUB_ACTIONS",
    "GIX_CREDENTIALS_HELPER_STDERR",
    "GIX_EXTERNAL_COMMAND_STDERR",
    "GIX_OBJECT_CACHE_MEMORY",
    "GIX_PACK_CACHE_MEMORY",
    "GIX_TEST_CREATE_ARCHIVES_EVEN_ON_CI",
    "GIX_TEST_EXPECT_REDUCED_TRUST",
    "GIX_TEST_IGNORE_ARCHIVES",
    "GIX_VERSION",
]

[target.s390x-unknown-linux-gnu]
image = "cross-rs-gitoxide:s390x-unknown-linux-gnu"
