[package]
name = "gitoxide-core"
description = "The library implementating all capabilities of the gitoxide CLI"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
license = "MIT"
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
git-repository = { version = "0.1.0", path = "../git-repository" }
git-odb = { version = "0.1.0", path = "../git-odb" }
git-features = { version = "0.1.0", path = "../git-features" }
anyhow = "1.0.31"
