[package]
name = "gitoxide-core"
description = "The library implementating all capabilities of the gitoxide CLI"
repository = "https://github.com/Byron/gitoxide"
version = "0.8.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
doctest = false
test = false

[features]
serde1 = ["git-commitgraph/serde1", "git-object/serde1", "git-odb/serde1", "git-protocol/serde1", "serde_json", "serde"]
organize = ["git-url", "bstr", "jwalk"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
git-repository = { version = "^0.5.0", path = "../git-repository" }
git-object = { version = "^0.7.0", path = "../git-object" }
git-hash = { version = "^0.2.0", path = "../git-hash" }
git-odb = { version = "^0.11.0", path = "../git-odb", features = ["pack-cache-lru-static"] }
git-protocol = { version = "^0.6.0", path = "../git-protocol" }
git-features = { version = "^0.12.0", path = "../git-features" }
git-commitgraph = { version = "^0.4.0", path = "../git-commitgraph" }
git-config = { version = "^0.1.0", path = "../git-config" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
anyhow = "1.0.31"
quick-error = "2.0.0"
bytesize = "1.0.1"
serde_json = { version = "1.0.56", optional = true }

# for 'organize' functionality
git-url = { version = "^0.3.0", path = "../git-url", optional = true }
bstr = { version = "0.2.14", features = ["unicode"], optional = true }
jwalk = { version = "0.6.0", optional = true }
