[package]
name = "git-object"
version = "0.4.0"
description = "Borrowed and owned git objects with deserialization and serialization support"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/Byron/git-oxide"
license = "MIT/Apache-2.0"
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[features]
serde1 = ["serde", "bstr/serde1", "smallvec/serde"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
git-ref = { version = "^0.4.0", path = "../git-ref" }
quick-error = "2.0.0"
hex = "0.4.2"
btoi = "0.4.2"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
nom = { version = "6.0.0-alpha1", default-features = false, features = ["alloc"]}
smallvec = "1.4.0"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
itoa = "0.4.6"

[dev-dependencies]
pretty_assertions = "0.6.1"
