[package]
name = "git-quote"
version = "0.4.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "Please use `gix-<thiscrate>` instead ('git' -> 'gix')"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.64"

[lib]
doctest = false

[dependencies]
bstr = { version = "1.0.1", default-features = false, features = ["std"]}
quick-error = "2.0.0"
btoi = "0.4.2"
