[package]
name = "git-tempfile"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A tempfile implementation with a global registry to assure cleanup"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0.2"
once_cell = { version = "1.8.0", default-features = false, features = ["race"] }
quick-error = "2.0.0"
signal-hook = { version = "0.3.9", default-features = false }
tempfile = "3.2.0"

[dev-dependencies]
git-testtools = { version = "^0.3", path = "../tests/tools" }
