[package]
name = "git-repository"
repository = "https://github.com/Byron/git-oxide"
description = "Manipulation of git repositories"
license = "MIT"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "src/assets/**"]

[lib]
doctest = false
test = false

[dependencies]
quick-error = { version = "1.2.3", git = "https://github.com/tailhook/quick-error", rev = "aad5701556438218339fba452451ae63a47c31c2" }
