[package]
name = "git-repository"
repository = "https://github.com/Byron/git-oxide"
description = "Manipulation of git repositories"
license = "MIT"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "src/assets/**"]

[lib]
doctest = false
test = false

[dependencies]
quick-error = "2.0.0"
