[package]
name = "git-repository"
repository = "https://github.com/Byron/gitoxide"
description = "Abstractions for git repositories"
license = "MIT/Apache-2.0"
version = "0.5.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "src/assets/**"]

[lib]
doctest = false
test = true

[dependencies]
git-ref = { version = "0.5.0", path = "../git-ref" }
git-odb = { version = "^0.16", path = "../git-odb" }
quick-error = "2.0.0"

[dev-dependencies]
git-testtools = { version = "0.1", path = "../tests/tools" }
