[package]
name = "gix-archive"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "implements archive generation from of a tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.64"

[lib]
doctest = false

[dependencies]
thiserror = "1.0.26"
gix-hash = { version = "^0.10.3", path = "../gix-hash" }
gix-object = { version = "^0.28.0", path = "../gix-object" }
