[package]
name = "gix-filter"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.11.3", path = "../gix-hash" }
gix-object = { version = "^0.31.0", path = "../gix-object" }

bstr = { version = "1.5.0", default-features = false, features = ["std"] }
thiserror = "1.0.38"
