[package]
name = "git-odb"
version = "0.14.0"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT/Apache-2.0"
description = "Implements a git object database for loose objects and packs"
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[features]
default = ["flate2/zlib-ng-compat"]
pack-cache-lru-static = ["uluru"]
pack-cache-lru-dynamic = ["memory-lru"]
serde1 = ["serde", "git-object/serde1"]
internal-testing-git-features-parallel = ["git-features/parallel"]

[[test]]
name = "multi-threaded"
path = "tests/odb-multi-threaded.rs"
required-features = ["internal-testing-git-features-parallel"]

[[test]]
name = "single-threaded"
path = "tests/odb-single-threaded.rs"
required-features = []

[package.metadata.docs.rs]
all-features = true

[dependencies]
git-object = { version = "^0.8.0", path = "../git-object" }
git-hash = { version = "^0.3.0", path = "../git-hash" }
git-features = { version = "^0.14.0", path = "../git-features" }

flate2 = { version = "1.0.17", default-features = false }
smallvec = "1.3.0"
filebuffer = "0.4.0"
byteorder = "1.2.3"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
btoi = "0.4.2"
itoa = "0.4.6"
bytesize = "1.0.1"
tempfile = "3.1.0"
parking_lot = { version = "0.11.0", default-features = false }
thiserror = "1.0.20"
uluru = { version = "2.0.0", optional = true }
memory-lru = { version = "0.1.0", optional = true }

[dev-dependencies]
pretty_assertions = "0.7.1"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
hex = "0.4.2"
common_macros = "0.1.1"
git-testtools = { version = "0.1", path = "../tests/tools"}
