[package]
name = "git-odb"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
edition = "2018"

[dependencies]
quick-error = "1.2.3"
walkdir = "2.1.4"
hex = "0.3.2"
miniz_oxide = "0.3.6"
smallvec = "1.3.0"
filebuffer = "0.4.0"
byteorder = "1.2.3"
itertools = "0.9.0"

[dev-dependencies]
anyhow = "1.0.31"
rayon = "1.3.0"
