[package]
name = "git-odb"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
edition = "2018"

[lib]
doctest = false

[features]
default = ["minimal-sha1"]
minimal-sha1 = ["sha1"]
fast-sha1 = ["fastsha1"]

[dependencies]
quick-error = "1.2.3"
walkdir = "2.1.4"
miniz_oxide = "0.3.6"
smallvec = "1.3.0"
filebuffer = "0.4.0"
byteorder = "1.2.3"
git-object = { version = "0.1.0", path = "../git-object" }
btoi = "0.4.2"
sha1 = { version = "0.6.0", optional = true }
fastsha1 = { package = "sha-1", version = "0.9.1", optional = true }

[dev-dependencies]
pretty_assertions = "0.6.1"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
hex = "0.4.2"
