[package]
name = "git-odb"
version = "0.1.0"
repository = "https://github.com/Byron/git-oxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
description = "Implements a git object database for loose objects and packs"
edition = "2018"

[lib]
doctest = false

[features]
serde1 = ["serde", "git-object/serde1"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
quick-error = "1.2.3"
walkdir = "2.1.4"
miniz_oxide = "0.3.6"
smallvec = "1.3.0"
filebuffer = "0.4.0"
byteorder = "1.2.3"
git-object = { version = "0.1.0", path = "../git-object" }
git-features = { version = "0.1.0", path = "../git-features" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
btoi = "0.4.2"
uluru = "0.4.0"
itoa = "0.4.6"
bytesize = "1.0.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
hex = "0.4.2"
common_macros = "0.1.1"
