[package]
name = "git-diff"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated to implementing differences between things"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/lib.rs"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-hash = { version = "^0.2.0", path = "../git-hash" }
git-object = { version = "0.7", path = "../git-object" }
git-odb = { version = "0.12", path = "../git-odb" }
petgraph = { version = "0.5.1", default-features = false }
quick-error = "2.0.0"

[dev-dependencies]
test-tools = { path = "../tests/tools" }
