[package]
name = "git-prompt"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for handling prompts in the terminal"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
thiserror = "1.0.32"
bstr = { version = "0.2.17", default-features = false, features = ["std"] }

[dev-dependencies]
expectrl = "0.5.2"
