[package]
name = "utils"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-repository = { version = "^0.7", path = "../../git-repository" }
git-lock = { version = "^0.3.0", path = "../../git-lock" }
anyhow = "1.0.42"
argh = { version = "0.1.5", default-features = false }
env_logger = { version = "0.9.0", default-features = false, features = ["humantime", "termcolor", "atty"] }
cargo_metadata = "0.14.0"
log = "0.4.14"
toml_edit = "0.2.1"
dia-semver = "9.0.0"
bstr = { version = "0.2.13", default-features = false, features = ["std", "unicode"]}
