[package]
name = "hours"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
git-odb = { version = "^0.14", path = "../../git-odb", features = ["pack-cache-lru-static", "pack-cache-lru-dynamic"]  }
git-traverse = { version = "0.1", path = "../../git-traverse" }
git-hash = { version = "^0.3", path = "../../git-hash" }
git-object = { version = "^0.8", path = "../../git-object" }
rayon = "1.5.0"
itertools = "0.10.0"
clap = { version = "=3.0.0-beta.2", default-features = true, features = ["wrap_help"] }
