[package]
name = "git-traverse"
version = "0.22.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "Please use `gix-<thiscrate>` instead ('git' -> 'gix')"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*"]
rust-version = "1.64"
autotests = false

[lib]
doctest = false

[dependencies]
git-hash = { version = "^0.10.3", path = "../git-hash" }
git-object = { version = "^0.26.2", path = "../git-object" }
git-hashtable = { version = "^0.1.2", path = "../git-hashtable" }
thiserror = "1.0.32"
