[package]
name = "git-features"
description = "A crate to integrate various capabilities using compile-time feature flags"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
publish = false
license = "MIT"
edition = "2018"

[lib]
doctest = false
test = false

[features]
parallel = ["flume", "crossbeam-utils", "crossbeam-channel", "num_cpus"]
fast-sha1 = ["fastsha1"]
progress-log = ["log"]
progress-prodash = ["prodash"]

[dependencies]
# 'parallel' feature
flume = { version = "0.7.1", optional = true, default-features = false }
crossbeam-utils = { version = "0.7.2", optional = true }
crossbeam-channel = { version = "0.4.2", optional = true }
num_cpus = { version = "1.13.0", optional = true }

# hashing and 'fast-sha1' feature
sha1 = "0.6.0"
crc = "1.8.1"
git-object = { version = "0.1.0", path = "../git-object" }
fastsha1 = { package = "sha-1", version = "0.9.1", optional = true }

# progress
log = { version = "0.4.8", optional = true }
prodash = { version = "4.0.4", optional = true, default-features = false }
