[package]
name = "git-features"
description = "A crate to integrate various capabilities using compile-time feature flags"
repository = "https://github.com/Byron/gitoxide"
version = "0.8.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
doctest = false
test = false

[features]
parallel = ["crossbeam-utils", "crossbeam-channel", "num_cpus", "jwalk"]
fast-sha1 = ["fastsha1"]
interrupt-handler = ["ctrlc"]
disable-interrupts = []
io-pipe = ["bytes"]

[[test]]
name = "parallel"
path = "tests/parallel.rs"
required-features = ["parallel"]

[[test]]
name = "pipe"
path = "tests/pipe.rs"
required-features = ["pipe"]

[dependencies]
git-object = { version = "^0.4.0", path = "../git-object", optional = true }

# 'parallel' feature
crossbeam-utils = { version = "0.8.0", optional = true }
crossbeam-channel = { version = "0.5.0", optional = true }
num_cpus = { version = "1.13.0", optional = true }

jwalk = { version = "0.5.1", optional = true }
walkdir = { version = "2.3.1" } # used when parallel is off

# hashing and 'fast-sha1' feature
sha1 = "0.6.0"
crc = "1.8.1"
fastsha1 = { package = "sha-1", version = "0.9.1", optional = true }

# progress
prodash = { version = "11.0.0", default-features = false, features = ["unit-bytes", "unit-human"] }

# interrupt-handler
ctrlc = { version = "3.1.4", optional = true, default-features = false, features = ['termination'] }

# pipe
bytes = { version = "0.6.0", optional = true }

[package.metadata.docs.rs]
all-features = true

