[package]
name = "git-protocol"
version = "0.0.0"
repository = "https://github.com/Byron/git-oxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for implementing git protocols"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"


[lib]
doctest = false

[dependencies]
quick-error = "2.0.0"
hex = "0.4.2"

[dev-dependencies]
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
