[package]
name = "git-protocol"
version = "0.0.0"
repository = "https://github.com/Byron/git-oxide"
license = "MIT"
description = "A WIP crate of the gitoxide project for implementing git protocols"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
