[package]
name = "git-protocol"
version = "0.8.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for implementing git protocols"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[features]
serde1 = ["serde", "bstr/serde1", "git-transport/serde1", "git-hash/serde1"]
blocking-client = ["git-transport/blocking-client"]

[[test]]
name = "blocking-client"
path = "tests/blocking-protocol.rs"
required-features = ["blocking-client"]

[[test]]
name = "common-client"
path = "tests/common-protocol.rs"
required-features = []

[dependencies]
git-features = { version = "^0.15.0", path = "../git-features", features = ["progress"] }
git-transport = { version = "^0.9.0", path = "../git-transport" }
git-hash = { version = "^0.3.0", path = "../git-hash" }

quick-error = "2.0.0"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
nom = { version = "6.0.0-alpha1", default-features = false, features = ["alloc"]}
btoi = "0.4.2"

[dev-dependencies]
git-packetline = { version = "^0.6.0", path = "../git-packetline" }
