name: AArch64 SIGSEGV experiment

on: push

jobs:
  test-fast:
    strategy:
      matrix:
        num-high: [ 0, 1, 2, 3 ]
        os-ver: [ '22.04', '24.04' ]
        channel: [ stable, beta ]  # `gix-macros::macros momo::ux` currently fails on `nightly`.
        get-rust-by: [ rt-action, curl-sh ]
        get-nextest-by: [ i-action, cargo-qi ]
        num-low: [ 0, 1, 2, 3 ]

      fail-fast: false

    runs-on: ubuntu-${{ matrix.os-ver }}-arm

    steps:
      - uses: actions/checkout@v4
      - if: matrix.get-rust-by == 'rt-action'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
      - if: matrix.get-rust-by == 'curl-sh'
        name: Install Rust via sh.rustup.rs
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
            sh -s -- -y --default-toolchain ${{ matrix.channel }}
          echo "PATH=$HOME/.cargo/bin:$PATH" >> "$GITHUB_ENV"
      # - uses: Swatinem/rust-cache@v2
      - if: matrix.get-nextest-by == 'i-action'
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - if: matrix.get-nextest-by == 'cargo-qi'
        name: Install nextest with quickinstall/binstall
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-binstall
          cargo quickinstall cargo-nextest
      - name: Test (nextest)
        env:
          GIX_TEST_CREATE_ARCHIVES_EVEN_ON_CI: '1'
        run: cargo nextest run --workspace --no-fail-fast
      - name: Doctest
        run: cargo test --workspace --doc --no-fail-fast
      - name: Check that tracked archives are up to date
        run: git diff --exit-code  # If this fails, the fix is usually to commit a regenerated archive.
