name: Rust

on:
  schedule: '0 13,1 * * *'

jobs:
  build-lint-test-benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: stress
      run: make stress
