name: Minimum Supported Rust Version

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-msrv:
    name: cargo check MSRV

    strategy:
      matrix:
        os:
          - windows-2022
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    env:
      # dictated by `firefox` to support the `helix` editor, but now probably effectively be controlled by `jiff`, which also aligns with `regex`.
      # IMPORTANT: adjust etc/msrv-badge.svg as well
      RUST_VERSION: 1.75.0

    defaults:
      run:
        # Use `bash` even in the Windows job, so any failing command fails its step (due to `-e`).
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Set up ${{ env.RUST_VERSION }} (MSRV) and nightly toolchains
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }} nightly --profile minimal --no-self-update
          rustup default ${{ env.RUST_VERSION }}
      - name: Downgrade locked dependencies to lowest allowed versions
        run: |
          cargo +nightly update -Zminimal-versions  # TODO(msrv): Use non-`-Z` way when available.
          git add Cargo.lock  # Stage for a later `git diff` check.
      - name: Run some `cargo check` commands on `gix`
        run: just ci-check-msrv
      - name: Check `cargo` didn't have to change the versions
        run: git diff --exit-code -- Cargo.lock
