name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lint-test-benchmark:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: cargo build
    - name: clippy
      run: cargo clippy
    - name: fmt
      run: cargo fmt --all --examples -- --check
    - name: test
      run: make tests
    - name: journey-tests
      run: make journey-tests
    - name: doc
      run: cargo doc
