name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lint-test-benchmark:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --all
    - name: fmt
      run: cargo fmt --all -- --check
    - name: test
      env:
        CI: true
      run: make tests
    - name: doc
      run: cargo doc
    - name: stress
      run: make stress
